<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="jest tests" tests="14" failures="4" errors="0" time="24.672">
  <testsuite name="GET /api/user/get/:id" errors="0" failures="0" skipped="0" timestamp="2024-12-04T13:24:17" time="22.611" tests="3">
    <testcase classname="GET /api/user/get/:id 200 - should return a user by ID" name="GET /api/user/get/:id 200 - should return a user by ID" time="0.126">
    </testcase>
    <testcase classname="GET /api/user/get/:id 404 - should return user not found" name="GET /api/user/get/:id 404 - should return user not found" time="0.015">
    </testcase>
    <testcase classname="GET /api/user/get/:id 500 - should return internal server error" name="GET /api/user/get/:id 500 - should return internal server error" time="0.01">
    </testcase>
  </testsuite>
  <testsuite name="GET /api/user/all" errors="0" failures="0" skipped="0" timestamp="2024-12-04T13:24:17" time="23.249" tests="2">
    <testcase classname="GET /api/user/all 200 " name="GET /api/user/all 200 " time="0.089">
    </testcase>
    <testcase classname="GET /api/user/all 500 " name="GET /api/user/all 500 " time="0.014">
    </testcase>
  </testsuite>
  <testsuite name="GET /api/user/check_auth" errors="0" failures="0" skipped="0" timestamp="2024-12-04T13:24:17" time="23.319" tests="5">
    <testcase classname="GET /api/user/check_auth 200 - should return user data if token is valid" name="GET /api/user/check_auth 200 - should return user data if token is valid" time="0.091">
    </testcase>
    <testcase classname="GET /api/user/check_auth 401 - should return access denied if token is missing" name="GET /api/user/check_auth 401 - should return access denied if token is missing" time="0.012">
    </testcase>
    <testcase classname="GET /api/user/check_auth 404 - should return user not found if user does not exist" name="GET /api/user/check_auth 404 - should return user not found if user does not exist" time="0.022">
    </testcase>
    <testcase classname="GET /api/user/check_auth 500 - should return internal server error on exception" name="GET /api/user/check_auth 500 - should return internal server error on exception" time="0.013">
    </testcase>
    <testcase classname="GET /api/user/check_auth 500 - should return invalid signature if token is incorrect" name="GET /api/user/check_auth 500 - should return invalid signature if token is incorrect" time="0.015">
    </testcase>
  </testsuite>
  <testsuite name="POST /api/user/sign" errors="0" failures="4" skipped="0" timestamp="2024-12-04T13:24:17" time="23.721" tests="4">
    <testcase classname="POST /api/user/sign 404" name="POST /api/user/sign 404" time="0.128">
      <failure>Error: expect(received).toBe(expected) // Object.is equality

Expected: 404
Received: 400
    at toBe (/app/test/controllers/user/user.login.test.js:33:33)
    at call (/app/test/controllers/user/user.login.test.js:2:1)
    at Generator.tryCatch (/app/test/controllers/user/user.login.test.js:2:1)
    at Generator._invoke [as next] (/app/test/controllers/user/user.login.test.js:2:1)
    at asyncGeneratorStep (/app/test/controllers/user/user.login.test.js:2:1)
    at asyncGeneratorStep (/app/test/controllers/user/user.login.test.js:2:1)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)</failure>
    </testcase>
    <testcase classname="POST /api/user/sign 501" name="POST /api/user/sign 501" time="0.077">
      <failure>Error: expect(received).toBe(expected) // Object.is equality

Expected: 501
Received: 400
    at toBe (/app/test/controllers/user/user.login.test.js:49:33)
    at call (/app/test/controllers/user/user.login.test.js:2:1)
    at Generator.tryCatch (/app/test/controllers/user/user.login.test.js:2:1)
    at Generator._invoke [as next] (/app/test/controllers/user/user.login.test.js:2:1)
    at asyncGeneratorStep (/app/test/controllers/user/user.login.test.js:2:1)
    at asyncGeneratorStep (/app/test/controllers/user/user.login.test.js:2:1)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)</failure>
    </testcase>
    <testcase classname="POST /api/user/sign 400" name="POST /api/user/sign 400" time="0.047">
      <failure>Error: expect(received).toEqual(expected) // deep equality

- Expected  - 2
+ Received  + 2

  Object {
-   &quot;details&quot;: &quot;Invalid password.&quot;,
-   &quot;error&quot;: &quot;Wrong Credentials!&quot;,
+   &quot;details&quot;: &quot;Le mot de passe est invalide.&quot;,
+   &quot;error&quot;: &quot;Identifiants incorrects.&quot;,
  }
    at toEqual (/app/test/controllers/user/user.login.test.js:78:31)
    at call (/app/test/controllers/user/user.login.test.js:2:1)
    at Generator.tryCatch (/app/test/controllers/user/user.login.test.js:2:1)
    at Generator._invoke [as next] (/app/test/controllers/user/user.login.test.js:2:1)
    at asyncGeneratorStep (/app/test/controllers/user/user.login.test.js:2:1)
    at asyncGeneratorStep (/app/test/controllers/user/user.login.test.js:2:1)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)</failure>
    </testcase>
    <testcase classname="POST /api/user/sign 200" name="POST /api/user/sign 200" time="0.233">
      <failure>Error: expect(received).toEqual(expected) // deep equality

- Expected  - 0
+ Received  + 4

  Object {
+   &quot;message&quot;: &quot;Connexion r√©ussie.&quot;,
+   &quot;token&quot;: &quot;eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwicm9sZSI6InVzZXIiLCJpYXQiOjE3MzMzMTg2ODEsImV4cCI6MTczMzQwNTA4MX0.A-wBbBX5dtA6-7_q0OafFbcigbr5KOpzAcpkPBr-AOs&quot;,
+   &quot;user&quot;: Object {
      &quot;email&quot;: &quot;john.doe@example.com&quot;,
      &quot;firstName&quot;: &quot;John&quot;,
      &quot;id&quot;: 4,
      &quot;lastName&quot;: &quot;Doe&quot;,
      &quot;role&quot;: &quot;user&quot;,
+   },
  }
    at toEqual (/app/test/controllers/user/user.login.test.js:115:31)
    at call (/app/test/controllers/user/user.login.test.js:2:1)
    at Generator.tryCatch (/app/test/controllers/user/user.login.test.js:2:1)
    at Generator._invoke [as next] (/app/test/controllers/user/user.login.test.js:2:1)
    at asyncGeneratorStep (/app/test/controllers/user/user.login.test.js:2:1)
    at asyncGeneratorStep (/app/test/controllers/user/user.login.test.js:2:1)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)</failure>
    </testcase>
  </testsuite>
</testsuites>